export const moduleConfig = {
    family: {
        title: 'Family',
        tag: 'Family',
        groupByKey: 'family_name',
        resultsTable: 'rfamily2',
        resultsIdColumn: 'run_id',
    },
    palmdb: {
        title: 'Palmdb',
        tag: 'Palmdb',
        groupByKey: 'sotu',
        resultsTable: 'palm_sra2',
        resultsIdColumn: 'run_id',
    },
    date: {
        title: 'Collection date',
        tag: 'Date',
        groupByKey: 'release_date',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
    },
    geography: {
        title: 'Geography',
        tag: 'Geography',
        groupByKey: 'geo',
        resultsTable: 'biosample_geo_coordinates',
        resultsIdColumn: 'biosample_id',
    },
    ecology: {
        title: 'Ecological zone',
        tag: 'Ecology',
        groupByKey: 'geo',
        resultsTable: 'biosample_geo_coordinates',
        resultsIdColumn: 'biosample_id',
    },
    tissue: {
        title: 'Tissue',
        tag: 'Tissue',
        groupByKey: 'tissue',
        resultsTable: 'biosample_tissue',
        resultsIdColumn: 'biosample_id',
    },
    host: {
        title: 'Organsim label',
        tag: 'Organism',
        groupByKey: 'host_label',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
    },
    statHost: {
        title: 'STAT Host',
        tag: 'STAT Host',
        groupByKey: 'stat_host_order',
        resultsTable: 'sra_stat',
        resultsIdColumn: 'run',
    },
    bioproject: {
        title: 'Bioproject',
        tag: 'Bioproject',
        groupByKey: 'bioproject',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
    },
};
