export const moduleConfig = {
    family: {
        title: 'Family',
        tag: 'Family',
        groupByKey: 'family_name',
        resultsTable: 'rfamily2',
        resultsIdColumn: 'run_id',
        defaultDisplay: 'table',
    },
    palmdb: {
        title: 'Palmdb',
        tag: 'Palmdb',
        groupByKey: 'sotu',
        resultsTable: 'palm_sra2',
        resultsIdColumn: 'run_id',
        defaultDisplay: 'table',
    },
    date: {
        title: 'Collection date',
        tag: 'Date',
        groupByKey: 'release_date',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
        defaultDisplay: 'table',
    },
    geography: {
        title: 'Geography',
        tag: 'Geography',
        groupByKey: 'geo',
        resultsTable: 'biosample_geo_coordinates',
        resultsIdColumn: 'biosample_id',
        defaultDisplay: 'table',
    },
    tissue: {
        title: 'Tissue',
        tag: 'Tissue',
        groupByKey: 'tissue',
        resultsTable: 'biosample_tissue',
        resultsIdColumn: 'biosample_id',
        defaultDisplay: 'table',
    },
    host: {
        title: 'Organism label',
        tag: 'Organism',
        groupByKey: 'host_label',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
        defaultDisplay: 'table',
    },
    statHost: {
        title: 'STAT Host',
        tag: 'STAT Host',
        groupByKey: 'stat_host_order',
        resultsTable: 'sra_stat',
        resultsIdColumn: 'run',
        defaultDisplay: 'table',
    },
    bioproject: {
        title: 'Bioproject',
        tag: 'Bioproject',
        groupByKey: 'bioproject',
        resultsTable: 'srarun',
        resultsIdColumn: 'run',
        defaultDisplay: 'table',
    },
};

export const sectionToModules = {
    'SRA Run': ['host', 'bioproject', 'date'],
    'Virus': ['family', 'palmdb'],
    'Environment': ['geography'],
    'Host': ['statHost', 'tissue'],
};
