name: Deploy serverless API
on:
push:
  branches:
    - main
  paths:
    - "api/**"
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - name: Build
        run: |
          cd api &&  zip -r build.zip .
      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: open-virome-api
          zip_file: api/build.zip
          memory_size: 128
          timeout: 10
          runtime: nodejs16.x
